apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "watson.fullname" . }}
  labels:
    {{- include "watson.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "watson.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "watson.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "watson.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: backend
          persistentVolumeClaim:
            claimName: watson-backend-pvc
      containers:
        - name: watson-ui
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env: 
          {{- range $key, $value := .Values.envVars }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
          {{- end }}
          {{- range $key, $value := .Values.secretEnvVars }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: backend
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: backend
              containerPort: 8081
              protocol: TCP
          volumeMounts:
            - mountPath: /app
              name: backend
              readOnly: false
          env: 
          {{- range $key, $value := .Values.envVars }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
          {{- end }}
          {{- range $key, $value := .Values.secretEnvVars }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
