kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: watson-backend-pvc
  labels: 
    {{- include "watson.labels" . | nindent 4 }}
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
  storageClassName: "efs-watson"
