envVars:
  DB_USER: ""
  PUBLIC_GOOGLE_CLIENT_ID: ""
  PUBLIC_WATSON_BACKEND_URL: ""
  SLACK_CHANNEL: ""

backend:
  image:
    repository: ""
    pullPolicy: ""
    tag: ""

ui:
  image:
    repository:
    pullPolicy: ""
    tag: ""

ingress:
  enabled: true
  className: ingress-private
  labels:
    ingress-class: ingress-private
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
